name = "news-aggregator"
main = "src/worker.js"
compatibility_date = "2026-06-30"
workers_dev = false

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "NEWS_CACHE"
id = "86aef1c1040a4043b8d733ee21c593b7"
